data_dir:
data_name:
save_location:
project_name:

# Data Parameters
input_channels: 2
output_channels: 2
sequence_length: 24000
batch_size: 50

# Training Parameters
epochs: 100
device: gpu
learn_rate: 0.005
loss_function: ESR

# Model Parameters
model: WaveNetModel
num_channels: 16
dilation_depth: 17
num_blocks: 2
kernel_size: 5
